### PR TITLE
Fix duplicate argument definitions.

### LINKED ISSUE #114: `serve` and `lint` are broken

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #114 

Existing tests now catch duplicate argument definitions across all commands because the detection is done in the CLI constructor.

### CODE REVIEW

File: src/commands/lint.ts [hunk 1]
```diff
@@ -17,7 +17,39 @@ export class LintCommand implements Command {
...
+      type: String,
+      defaultValue: "bower.json",
+      description: (
+        "If inputs are specified, look for `config-field` in this JSON file."
+      )
+    },
+    {
+      name: "config-field",
+      type: String,
+      defaultValue: "main",
```
Comment (azakus) [inline src/commands/lint.ts]: This should be `entrypoint` now right?

**Comment by azakus** [comment]
LGTM
