### PR TITLE
Fix build bundling on windows

### LINKED ISSUE #222: Error in polymer build with the last release (v0.11.0)
With the last release (v0.11.0), `polymer build` doesn't work:

error

### LINKED ISSUE #227: polymer lint fails on basic element project layout
Hi!

I just followed the steps in the [docs](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#element) to create a new element project and when I try to lint the command fails in different ways.

Using the command [specified in the docs
](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#lint)
```
$ polymer lint --input my-el.html
error:   Uncaught exception: UNKNOWN_OPTION: Unknown option: --input
error:   UNKNOWN_OPTION: Unknown option: --input
    at halt (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:81:15)
    at Argv.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:72:7)
    at CommandLineArgs.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:57:10)
    at CommandLineCommands.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-commands/lib/command-line-commands.js:78:28)
    at PolymerCli.run (/usr/local/lib/node_modules/polymer-cli/lib/polymer-cli.js:115:35)
    at /usr/local/lib/node_modules/polymer-cli/bin/polymer.js:22:7
    at /usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)
garcianavalon at eva in ~/Development/my-el
```

Trying different options based on [the README of this repo](https://github.com/Polymer/polymer-cli#lint)
(I tried creating a polymer.json file with content `{"entrypoint": "my-el.html"}` but the result is the same)
```
$ polymer lint my-el.html
ERROR finding /Users/garcianavalon/Development/my-el/polymer/polymer.html
Error: ENOENT: no such file or directory, open '/Users/garcianavalon/Development/my-el/polymer/polymer.html'
    at Error (native)
```
```
$ polymer lint
ERROR finding /Users/garcianavalon/Development/my-el/polymer/polymer.html
Error: ENOENT: no such file or directory, open '/Users/garcianavalon/Development/my-el/polymer/polymer.html'
    at Error (native)
```

Looks like the import is not working properly
`<link rel="import" href="../polymer/polymer.html">`

I'm using latest version
```
$ polymer --version
0.11.0
```
Any idea on what could be wrong? 
Thanks for any help!
cheers.

### PR DESCRIPTION
**Pull request by FredKSchott**
Fixes #222

Previously, we were relying on path.posix.normalize() to convert unix & windows paths to the posix path format, to be returned as a URL path. However, path.posix.normalize() doesn't convert windows paths to posix. Example:

```
> path.posix.normalize('/src/123.html')
'/src/123.html'
> path.posix.normalize('\\src\\123.html')
'\\src\\123.html // expected url format `/src/123/html`
```

Both @justinfagnani  and I have looked into this, and the conclusion is that Node does not support this conversion natively. 

This commit adds the [slash](https://www.npmjs.com/package/slash) library to handle this conversion instead. This is a simple, well-supported package used by babel and some other major projects.

Our original worry was that escaped back slashes would be incorrectly converted, but Windows will actually not allow any slashes in file names, escaped or otherwise. See:
\- http://stackoverflow.com/a/10708449
\- https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

On Mac & Unix, backslashes are allowed in file names. This means that slash will not properly convert those strings:

```
> path.posix.normalize('/src/this_file_has_escaped\\_see.html')
'/src/this_file_has_escaped/_see.html'
```

However, the files we are converting and checking against are all meant for HTML import URL paths. Backward slashes are not allowed in URLs (RFC 2396) and most browsers will just convert them to forward slashes. So this case would already be erroneous, and as a result we do not really need to support it. One possible enhancement would be to throw a helpful error if we detect a backward slash in a posix formatted path, because right now we'll just silently convert it to a forward slash separator.

### CODE REVIEW

File: test/build/bundle_test.js [hunk 1]
```diff
@@ -97,6 +97,18 @@ suite('Bundler', () => {
     return link != null;
   };
 
+  suite('urlFromPath()', () => {
+
+    test.skip('creates a URL path relative to root when called with a file path', () => setupTest({
```
Comment (FredKSchott) [inline test/build/bundle_test.js]: Our testing setup currently can't test path-related behavior on Windows. My next task will be to make this test and the several under it runnable.

Comment (justinfagnani) [inline test/build/bundle_test.js]: rather than always skipping the test, can you conditionally skip it based on the platform?

**Comment by garlicnation** [comment]
LGTM - please add a TODO to explore getting rid of the added dependency.

File: test/build/bundle_test.js (hunk 1 above)
Comment (FredKSchott) [inline test/build/bundle_test.js]: good call, done

**Comment by FredKSchott** [comment]
Got rid of the dependency, its logic actually fit really well into the function itself

just waiting for tests to pass and then I'll merge
